backend:
  name: github
  repo: vags97/alena-diputada
media_folder: "docs/.vuepress/public/media"
public_folder: "/media"
publish_mode: editorial_workflow
collections:
  - label: "Home"
    name: "home"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "docs/index.md"
        delete: false
        fields:
          - { label: "Home", name: "home", widget: "hidden", default: true }
          - { label: "Titulo", name: "title", widget: "string" }
          - { label: "Imagen", name: "image", widget: "image", default: "/media/logo.png" }
          - { label: "Descripción", name: "description", widget: "string" }
          - { label: "Hero image", name: "heroImage", widget: "image", required: false }
          - { label: "Hero text", name: "heroText", widget: "string" }
          - { label: "Tags", name: "tags", widget: "list", required: false, default: ['Apruebo Dignidad'] }
          - { label: "Cuerpo", name: body, widget: markdown, required: false }
  - label: "Noticias"
    name: "noticias"
    folder: "docs/_noticias"
    create: true
    fields:
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", required: false, default: ['Apruebo Dignidad'] }
      - { label: "Fecha", name: "date", widget: "date" }
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Descripción", name: "description", widget: "string" }
      - { label: "Cuerpo", name: "body", widget: "markdown" }
  - label: "Candidatos\as Diputados\as"
    name: "diputados"
    folder: "docs/candidatos-diputados"
    create: true
    fields:
      - { label: "Diputado", name: "diputado", widget: "hidden", default: true }
      - { label: "Nombre", name: "title", widget: "string" }
      - { label: "Descripción Corta", name: "description", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", required: false, default: ['Apruebo Dignidad'] }
      - { label: "Imagen", name: "image", widget: "image", default: "/media/noProfile.png" }
      - label: "Distrito"
        name: "distrito"
        widget: "select"
        options: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28 ]
      - { label: "Papeleta", name: "papeleta", widget: "string" }
      - { label: "Página Web", name: "paginaWeb", widget: "string", required: false }
      - { label: "Facebook", name: "facebook", widget: "string", required: false }
      - { label: "Twitter", name: "twitter", widget: "string", required: false }
      - { label: "Instagram", name: "instagram", widget: "string", required: false }
      - { label: "Youtube", name: "youtube", widget: "string", required: false }
      - { label: "TikTok", name: "tiktok", widget: "string", required: false }
      - label: Propuestas
        name: propuestas
        widget: list
        required: false
        fields:
          - { label: "Título", name: "title", widget: "markdown" }
          - { label: "Descripcion", name: "description", widget: "markdown" }
      - { label: "Cuerpo", name: "body", widget: "markdown" }
  - label: "Candidatos\as Senadores\as"
    name: "diputados"
    folder: "docs/candidatos-senadores"
    create: true
    fields:
      - { label: "Senador", name: "senador", widget: "hidden", default: true }
      - { label: "Nombre", name: "title", widget: "string" }
      - { label: "Descripción Corta", name: "description", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", required: false, default: [ 'Apruebo Dignidad' ] }
      - { label: "Imagen", name: "image", widget: "image", default: "/media/noProfile.png" }
      - label: "Circunscripcion Senatorial"
        name: "circunscripcionSenatorial"
        widget: "select"
        options: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28 ]
      - { label: "Papeleta", name: "papeleta", widget: "string" }
      - { label: "Página Web", name: "paginaWeb", widget: "string", required: false }
      - { label: "Facebook", name: "facebook", widget: "string", required: false }
      - { label: "Twitter", name: "twitter", widget: "string", required: false }
      - { label: "Instagram", name: "instagram", widget: "string", required: false }
      - { label: "Youtube", name: "youtube", widget: "string", required: false }
      - { label: "TikTok", name: "tiktok", widget: "string", required: false }
      - label: Propuestas
        name: propuestas
        widget: list
        required: false
        fields:
        - { label: "Título", name: "title", widget: "markdown" }
        - { label: "Descripcion", name: "description", widget: "markdown" }
      - { label: "Cuerpo", name: "body", widget: "markdown" }
  - label: "Candidatos\as CORES"
    name: "cores"
    folder: "docs/candidatos-cores"
    create: true
    fields:
      - { label: "CORE", name: "core", widget: "hidden", default: true }
      - { label: "Nombre", name: "title", widget: "string" }
      - { label: "Descripción Corta", name: "description", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", required: false, default: [ 'Apruebo Dignidad' ] }
      - { label: "Imagen", name: "image", widget: "image", default: "/media/noProfile.png" }
      - label: "Circunscripcion Provincial"
        name: "circunscripcionProvincial"
        widget: "select"
        options: [
            'Antartica Chilena',
            'Magallanes',
            'Tierra Del Fuego',
            'Ultima Esperanza',
            'Aysen',
            'Capitan Prat',
            'Coyhaique',
            'General Carrera',
            'Llanquihue',
            'Osorno',
            'Chiloe',
            'Palena',
            'Ranco',
            'Valdivia',
            'Cautin II',
            'Malleco',
            'Cautin I',
            'Concepcion I',
            'Concepcion II',
            'Concepcion III',
            'Arauco',
            'Biobio',
            'Diguillin',
            'Itata',
            'Punilla',
            'Curico',
            'Talca',
            'Cauquenes',
            'Linares',
            'Cachapoal I',
            'Cachapoal II',
            'Cardenal Caro',
            'Colchagua',
            'Chacabuco',
            'Santiago I',
            'Santiago III',
            'Santiago II',
            'Santiago IV',
            'Santiago V',
            'Cordillera',
            'Santiago VI',
            'Maipo',
            'Melipilla',
            'Talagante',
            'Los Andes',
            'Marga Marga',
            'Petorca',
            'Quillota',
            'San Felipe',
            'Valparaiso I',
            'Isla De Pascua',
            'San Antonio',
            'Valparaiso II',
            'Choapa',
            'Elqui',
            'Limari',
            'Chañaral',
            'Copiapo',
            'Huasco',
            'Antofagasta',
            'El Loa',
            'Tocopilla',
            'Iquique',
            'Tamarugal',
            'Arica',
            'Parinacota'
        ]
      - { label: "Papeleta", name: "papeleta", widget: "string" }
      - { label: "Página Web", name: "paginaWeb", widget: "string", required: false }
      - { label: "Facebook", name: "facebook", widget: "string", required: false }
      - { label: "Twitter", name: "twitter", widget: "string", required: false }
      - { label: "Instagram", name: "instagram", widget: "string", required: false }
      - { label: "Youtube", name: "youtube", widget: "string", required: false }
      - { label: "TikTok", name: "tiktok", widget: "string", required: false }
      - { label: "Cuerpo", name: "body", widget: "markdown" }
      - { label: "Contactado/a", name: "contactado",  widget: "boolean" }
